name: Build

on:
  pull_request:
    paths-ignore:
      - "www/**"
      - ".github/workflows/www.yml"
  push:
    branches: [main]
    paths-ignore:
      - "www/**"
      - ".github/workflows/www.yml"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build
